# Generated by Django 2.1.7 on 2019-02-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190223_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(),
        ),
    ]
